// stephen-taipei-react/src/components/Contact.jsx
import React, { useState } from 'react';
import { Mail, Github, Linkedin, MapPin, Send, CheckCircle, AlertCircle } from 'lucide-react';
import { useLanguage } from '../i18n/LanguageContext';

const Contact = () => {
  const { t, language } = useLanguage();
  const [formState, setFormState] = useState({
    name: '',
    email: '',
    message: '',
  });
  const [submitStatus, setSubmitStatus] = useState(null); // null, 'success', 'error'
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormState(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);

    // Simulate form submission - replace with actual API call when backend is ready
    try {
      // For now, open mailto link as fallback
      const subject = encodeURIComponent(`Contact from ${formState.name}`);
      const body = encodeURIComponent(`Name: ${formState.name}\nEmail: ${formState.email}\n\nMessage:\n${formState.message}`);
      window.location.href = `mailto:contact@stephen.taipei?subject=${subject}&body=${body}`;

      setSubmitStatus('success');
      setFormState({ name: '', email: '', message: '' });
    } catch (error) {
      setSubmitStatus('error');
    } finally {
      setIsSubmitting(false);
      setTimeout(() => setSubmitStatus(null), 5000);
    }
  };

  const isChinese = language?.toLowerCase().startsWith('zh');

  return (
    <section id="contact" className="py-20 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">

          <div>
            <h2 className="text-3xl font-bold text-gray-900 mb-6">{t.contact.title}</h2>
            <p className="text-gray-600 mb-8 text-lg">
              {t.contact.subtitle}
            </p>

            <div className="space-y-6">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-blue-50 rounded-full flex items-center justify-center text-primary">
                  <Mail className="w-5 h-5" />
                </div>
                <div>
                  <p className="text-sm text-gray-500 font-medium">{t.contact.email}</p>
                  <a href="mailto:contact@stephen.taipei" className="text-gray-900 font-semibold hover:text-primary transition-colors">
                    contact@stephen.taipei
                  </a>
                </div>
              </div>

              <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-blue-50 rounded-full flex items-center justify-center text-primary">
                  <MapPin className="w-5 h-5" />
                </div>
                <div>
                  <p className="text-sm text-gray-500 font-medium">{t.contact.location}</p>
                  <p className="text-gray-900 font-semibold">{t.contact.locationValue}</p>
                </div>
              </div>

              <div className="flex gap-4 pt-4">
                <a
                  href="https://github.com/tw-stephen"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="w-10 h-10 border border-gray-200 rounded-full flex items-center justify-center text-gray-600 hover:bg-gray-50 hover:text-primary transition-colors"
                  aria-label="GitHub Profile"
                >
                  <Github className="w-5 h-5" />
                </a>
                <a
                  href="https://www.linkedin.com/in/stephen-chuang-taipei/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="w-10 h-10 border border-gray-200 rounded-full flex items-center justify-center text-gray-600 hover:bg-gray-50 hover:text-primary transition-colors"
                  aria-label="LinkedIn Profile"
                >
                  <Linkedin className="w-5 h-5" />
                </a>
              </div>
            </div>
          </div>

          <div className="bg-gray-50 p-8 rounded-2xl border border-gray-100">
            <form className="space-y-6" onSubmit={handleSubmit}>
              <div>
                <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-2">{t.contact.formName}</label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  value={formState.name}
                  onChange={handleInputChange}
                  required
                  className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-primary/20 focus:border-primary transition-colors outline-none bg-white"
                  placeholder={t.contact.formNamePlaceholder}
                />
              </div>
              <div>
                <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-2">{t.contact.formEmail}</label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  value={formState.email}
                  onChange={handleInputChange}
                  required
                  className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-primary/20 focus:border-primary transition-colors outline-none bg-white"
                  placeholder={t.contact.formEmailPlaceholder}
                />
              </div>
              <div>
                <label htmlFor="message" className="block text-sm font-medium text-gray-700 mb-2">{t.contact.formMessage}</label>
                <textarea
                  id="message"
                  name="message"
                  value={formState.message}
                  onChange={handleInputChange}
                  required
                  rows="4"
                  className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:ring-2 focus:ring-primary/20 focus:border-primary transition-colors outline-none bg-white"
                  placeholder={t.contact.formMessagePlaceholder}
                ></textarea>
              </div>

              {/* Submit Status Messages */}
              {submitStatus === 'success' && (
                <div className="flex items-center gap-2 p-3 bg-green-50 text-green-700 rounded-lg">
                  <CheckCircle className="w-5 h-5" />
                  <span className="text-sm font-medium">
                    {isChinese ? '郵件客戶端已開啟，請完成發送！' : 'Email client opened, please complete sending!'}
                  </span>
                </div>
              )}
              {submitStatus === 'error' && (
                <div className="flex items-center gap-2 p-3 bg-red-50 text-red-700 rounded-lg">
                  <AlertCircle className="w-5 h-5" />
                  <span className="text-sm font-medium">
                    {isChinese ? '發送失敗，請直接發送郵件至 contact@stephen.taipei' : 'Failed to send. Please email directly to contact@stephen.taipei'}
                  </span>
                </div>
              )}

              <button
                type="submit"
                disabled={isSubmitting}
                className="w-full px-6 py-3 bg-primary hover:bg-primary-dark text-white font-medium rounded-lg transition-colors shadow-lg shadow-blue-500/30 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {isSubmitting ? (
                  <>
                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    {isChinese ? '處理中...' : 'Sending...'}
                  </>
                ) : (
                  <>
                    <Send className="w-5 h-5" />
                    {t.contact.sendMessage}
                  </>
                )}
              </button>
            </form>
          </div>

        </div>
      </div>
    </section>
  );
};

export default Contact;

// src/app/components/contact/contact.component.ts
import { Component, ElementRef, AfterViewInit, ViewChild, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

gsap.registerPlugin(ScrollTrigger);

interface ContactForm {
  name: string;
  email: string;
  subject: string;
  message: string;
}

interface SocialLink {
  name: string;
  url: string;
  icon: string;
}

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './contact.component.html',
  styleUrl: './contact.component.scss'
})
export class ContactComponent implements AfterViewInit {
  @ViewChild('contactSection') contactSection!: ElementRef;

  isSubmitting = signal(false);
  isSubmitted = signal(false);

  form: ContactForm = {
    name: '',
    email: '',
    subject: '',
    message: ''
  };

  socialLinks: SocialLink[] = [
    {
      name: 'GitHub',
      url: 'https://github.com',
      icon: 'M12 0C5.374 0 0 5.373 0 12c0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23A11.509 11.509 0 0112 5.803c1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576C20.566 21.797 24 17.3 24 12c0-6.627-5.373-12-12-12z'
    },
    {
      name: 'LinkedIn',
      url: 'https://linkedin.com',
      icon: 'M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z'
    },
    {
      name: 'Email',
      url: 'mailto:contact@stephen.taipei',
      icon: 'M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z'
    }
  ];

  ngAfterViewInit() {
    this.initAnimations();
  }

  async onSubmit() {
    if (!this.form.name || !this.form.email || !this.form.message) {
      return;
    }

    this.isSubmitting.set(true);

    // Simulate form submission
    await new Promise(resolve => setTimeout(resolve, 1500));

    this.isSubmitting.set(false);
    this.isSubmitted.set(true);

    // Reset after showing success
    setTimeout(() => {
      this.isSubmitted.set(false);
      this.form = { name: '', email: '', subject: '', message: '' };
    }, 3000);
  }

  private initAnimations() {
    const section = this.contactSection.nativeElement;

    gsap.from(section.querySelectorAll('.animate-on-scroll'), {
      scrollTrigger: {
        trigger: section,
        start: 'top 80%',
        toggleActions: 'play none none none'
      },
      opacity: 0,
      y: 50,
      duration: 0.8,
      stagger: 0.2,
      ease: 'power3.out'
    });
  }
}

<section id="contact" #contactSection class="py-24 md:py-32 relative">
  <div class="container mx-auto px-4">
    <!-- Section Header -->
    <div class="text-center mb-16">
      <h2 class="section-title animate-on-scroll">
        <span class="text-gradient">聯絡我</span>
      </h2>
      <p class="section-subtitle animate-on-scroll">Get In Touch</p>
    </div>

    <div class="max-w-5xl mx-auto grid lg:grid-cols-2 gap-12">
      <!-- Contact Info -->
      <div class="animate-on-scroll space-y-8">
        <div>
          <h3 class="text-2xl font-bold text-white mb-4">讓我們合作</h3>
          <p class="text-gray-400 leading-relaxed">
            無論是專案諮詢、技術合作，或是職涯機會，歡迎與我聯繫。
            我會盡快回覆您的訊息。
          </p>
        </div>

        <!-- Contact Methods -->
        <div class="space-y-4">
          <div class="flex items-center gap-4 p-4 glass-card rounded-xl">
            <div class="w-12 h-12 rounded-lg bg-neon-cyan/20 flex items-center justify-center">
              <svg class="w-6 h-6 text-neon-cyan" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
            </div>
            <div>
              <p class="text-sm text-gray-400">Email</p>
              <a href="mailto:contact@stephen.taipei" class="text-white hover:text-neon-cyan transition-colors">
                contact&#64;stephen.taipei
              </a>
            </div>
          </div>

          <div class="flex items-center gap-4 p-4 glass-card rounded-xl">
            <div class="w-12 h-12 rounded-lg bg-neon-pink/20 flex items-center justify-center">
              <svg class="w-6 h-6 text-neon-pink" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
            </div>
            <div>
              <p class="text-sm text-gray-400">Location</p>
              <span class="text-white">台灣 Taiwan</span>
            </div>
          </div>
        </div>

        <!-- Social Links -->
        <div>
          <p class="text-gray-400 mb-4">社群連結</p>
          <div class="flex gap-4">
            @for (social of socialLinks; track social.name) {
              <a
                [href]="social.url"
                target="_blank"
                rel="noopener noreferrer"
                class="w-12 h-12 rounded-lg glass-card flex items-center justify-center text-gray-400 hover:text-neon-cyan hover:border-neon-cyan transition-all group"
                [attr.aria-label]="social.name"
              >
                @if (social.name === 'Email') {
                  <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" [attr.d]="social.icon" />
                  </svg>
                } @else {
                  <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                    <path [attr.d]="social.icon" />
                  </svg>
                }
              </a>
            }
          </div>
        </div>
      </div>

      <!-- Contact Form -->
      <div class="animate-on-scroll">
        <form (ngSubmit)="onSubmit()" class="glass-card rounded-2xl p-8 space-y-6">
          <!-- Success Message -->
          @if (isSubmitted()) {
            <div class="text-center py-8 animate-scale-in">
              <div class="w-16 h-16 mx-auto mb-4 rounded-full bg-neon-cyan/20 flex items-center justify-center">
                <svg class="w-8 h-8 text-neon-cyan" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <h4 class="text-xl font-bold text-white mb-2">訊息已送出！</h4>
              <p class="text-gray-400">感謝您的來信，我會盡快回覆。</p>
            </div>
          } @else {
            <!-- Name -->
            <div>
              <label for="name" class="block text-sm font-medium text-gray-300 mb-2">姓名 *</label>
              <input
                type="text"
                id="name"
                name="name"
                [(ngModel)]="form.name"
                required
                class="w-full px-4 py-3 rounded-lg bg-deep-space/50 border border-gray-700 text-white placeholder-gray-500 focus:border-neon-cyan focus:ring-1 focus:ring-neon-cyan outline-none transition-colors"
                placeholder="您的姓名"
              />
            </div>

            <!-- Email -->
            <div>
              <label for="email" class="block text-sm font-medium text-gray-300 mb-2">Email *</label>
              <input
                type="email"
                id="email"
                name="email"
                [(ngModel)]="form.email"
                required
                class="w-full px-4 py-3 rounded-lg bg-deep-space/50 border border-gray-700 text-white placeholder-gray-500 focus:border-neon-cyan focus:ring-1 focus:ring-neon-cyan outline-none transition-colors"
                placeholder="your@email.com"
              />
            </div>

            <!-- Subject -->
            <div>
              <label for="subject" class="block text-sm font-medium text-gray-300 mb-2">主旨</label>
              <input
                type="text"
                id="subject"
                name="subject"
                [(ngModel)]="form.subject"
                class="w-full px-4 py-3 rounded-lg bg-deep-space/50 border border-gray-700 text-white placeholder-gray-500 focus:border-neon-cyan focus:ring-1 focus:ring-neon-cyan outline-none transition-colors"
                placeholder="訊息主旨"
              />
            </div>

            <!-- Message -->
            <div>
              <label for="message" class="block text-sm font-medium text-gray-300 mb-2">訊息 *</label>
              <textarea
                id="message"
                name="message"
                [(ngModel)]="form.message"
                required
                rows="5"
                class="w-full px-4 py-3 rounded-lg bg-deep-space/50 border border-gray-700 text-white placeholder-gray-500 focus:border-neon-cyan focus:ring-1 focus:ring-neon-cyan outline-none transition-colors resize-none"
                placeholder="請輸入您的訊息..."
              ></textarea>
            </div>

            <!-- Submit Button -->
            <button
              type="submit"
              [disabled]="isSubmitting()"
              class="w-full btn-primary flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              @if (isSubmitting()) {
                <svg class="w-5 h-5 animate-spin" fill="none" viewBox="0 0 24 24">
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                <span>送出中...</span>
              } @else {
                <span>送出訊息</span>
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
                </svg>
              }
            </button>
          }
        </form>
      </div>
    </div>
  </div>

  <!-- Background Decoration -->
  <div class="absolute top-1/2 left-0 w-96 h-96 bg-deep-purple/10 rounded-full blur-3xl -translate-y-1/2"></div>
  <div class="absolute bottom-0 right-1/4 w-72 h-72 bg-neon-cyan/5 rounded-full blur-3xl"></div>
</section>
