// src/app/components/navbar/navbar.component.ts
import { Component, signal, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.scss'
})
export class NavbarComponent {
  isScrolled = signal(false);
  isMobileMenuOpen = signal(false);

  navLinks = [
    { label: '關於我', href: '#about' },
    { label: '技能', href: '#skills' },
    { label: '經歷', href: '#experience' },
    { label: '作品集', href: '#portfolio' },
    { label: '成就', href: '#achievements' },
    { label: '聯絡', href: '#contact' },
  ];

  @HostListener('window:scroll')
  onWindowScroll() {
    this.isScrolled.set(window.scrollY > 50);
  }

  toggleMobileMenu() {
    this.isMobileMenuOpen.update(v => !v);
  }

  closeMobileMenu() {
    this.isMobileMenuOpen.set(false);
  }

  scrollTo(href: string, event: Event) {
    event.preventDefault();
    const element = document.querySelector(href);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
      this.closeMobileMenu();
    }
  }
}

<nav
  class="fixed top-0 left-0 right-0 z-50 transition-all duration-300"
  [class.bg-deep-space]="isScrolled()"
  [class.bg-opacity-90]="isScrolled()"
  [class.backdrop-blur-lg]="isScrolled()"
  [class.shadow-lg]="isScrolled()"
  [class.shadow-neon-cyan/10]="isScrolled()"
>
  <div class="container mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-20">
      <!-- Logo -->
      <a href="#" class="flex items-center space-x-2 group" (click)="scrollTo('#hero', $event)">
        <span class="text-2xl font-bold font-display text-gradient">S.</span>
        <span class="hidden sm:block text-lg font-medium text-gray-300 group-hover:text-neon-cyan transition-colors">
          Stephen
        </span>
      </a>

      <!-- Desktop Navigation -->
      <div class="hidden md:flex items-center space-x-8">
        @for (link of navLinks; track link.href) {
          <a
            [href]="link.href"
            class="nav-link relative text-gray-300 hover:text-neon-cyan transition-colors duration-300 font-medium"
            (click)="scrollTo(link.href, $event)"
          >
            {{ link.label }}
            <span class="nav-underline absolute bottom-0 left-0 w-0 h-0.5 bg-gradient-to-r from-neon-cyan to-neon-pink transition-all duration-300"></span>
          </a>
        }
      </div>

      <!-- CTA Button -->
      <div class="hidden md:block">
        <a
          href="#contact"
          class="btn-primary text-sm"
          (click)="scrollTo('#contact', $event)"
        >
          聯絡我
        </a>
      </div>

      <!-- Mobile Menu Button -->
      <button
        class="md:hidden p-2 text-gray-300 hover:text-neon-cyan transition-colors"
        (click)="toggleMobileMenu()"
        [attr.aria-expanded]="isMobileMenuOpen()"
        aria-label="Toggle menu"
      >
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          @if (isMobileMenuOpen()) {
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          } @else {
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          }
        </svg>
      </button>
    </div>
  </div>

  <!-- Mobile Menu -->
  @if (isMobileMenuOpen()) {
    <div class="md:hidden glass-card border-t border-neon-cyan/20 animate-fade-in-up">
      <div class="container mx-auto px-4 py-4 space-y-4">
        @for (link of navLinks; track link.href) {
          <a
            [href]="link.href"
            class="block py-2 text-gray-300 hover:text-neon-cyan transition-colors font-medium"
            (click)="scrollTo(link.href, $event)"
          >
            {{ link.label }}
          </a>
        }
        <a
          href="#contact"
          class="block btn-primary text-center text-sm mt-4"
          (click)="scrollTo('#contact', $event)"
        >
          聯絡我
        </a>
      </div>
    </div>
  }
</nav>

// stephen-taipei-react/src/components/Navbar.jsx
import React, { useState } from 'react';
import { createPortal } from 'react-dom';
import { Menu, X, Globe } from 'lucide-react';
import { useLanguage, LANGUAGE_OPTIONS } from '../i18n/LanguageContext';

const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);
  const { language, setLanguage, t } = useLanguage();

  const navLinks = [
    { name: t.nav.about, href: '#about' },
    { name: t.nav.skills, href: '#skills' },
    { name: t.nav.experience, href: '#experience' },
    { name: t.nav.portfolio, href: '#portfolio' },
    { name: t.nav.tools, href: '#tools' },
    { name: t.nav.contact, href: '#contact' },
  ];

  return (
    <>
      {/* Mobile menu backdrop overlay - rendered via portal to body */}
      {isOpen && createPortal(
        <div
          className="fixed inset-0 bg-black/50 md:hidden"
          style={{ zIndex: 40 }}
          onClick={() => setIsOpen(false)}
        />,
        document.body
      )}
      <nav className="fixed w-full bg-white/90 backdrop-blur-sm shadow-sm z-50 border-b border-gray-100">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          <div className="flex-shrink-0">
            <button
              onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
              className="text-2xl font-bold bg-gradient-to-r from-primary-dark to-secondary bg-clip-text text-transparent cursor-pointer hover:opacity-80 transition-opacity"
            >
              Stephen.Taipei
            </button>
          </div>

          <div className="hidden md:flex items-center gap-6">
            <div className="flex items-baseline space-x-6">
              {navLinks.map((link) => (
                <a
                  key={link.href}
                  href={link.href}
                  className="text-gray-600 hover:text-primary-dark px-3 py-2 rounded-md text-sm font-medium transition-colors duration-200"
                >
                  {link.name}
                </a>
              ))}
            </div>

            {/* Language Switcher */}
            <div className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-gray-600 border border-gray-200 rounded-full hover:border-primary/30 transition-all">
              <Globe className="w-4 h-4" />
              <select
                value={language}
                onChange={(e) => setLanguage(e.target.value)}
                className="bg-transparent outline-none cursor-pointer"
                aria-label="Select language"
              >
                {LANGUAGE_OPTIONS.map((lang) => (
                  <option key={lang.value} value={lang.value}>
                    {lang.label}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div className="flex items-center gap-2 md:hidden">
            {/* Mobile Language Switcher */}
            <div className="p-2 text-gray-600 hover:text-primary-dark">
              <label htmlFor="mobile-language" className="sr-only">
                Select language
              </label>
              <div className="flex items-center border border-gray-200 rounded-md px-2 py-1">
                <Globe className="w-5 h-5 mr-2" />
                <select
                  id="mobile-language"
                  value={language}
                  onChange={(e) => setLanguage(e.target.value)}
                  className="bg-transparent text-sm outline-none"
                  aria-label="Select language"
                >
                  {LANGUAGE_OPTIONS.map((lang) => (
                    <option key={lang.value} value={lang.value}>
                      {lang.label}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <button
              onClick={() => setIsOpen(!isOpen)}
              className="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none"
            >
              {isOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
            </button>
          </div>
        </div>
      </div>

      {/* Mobile menu */}
      {isOpen && (
        <div className="md:hidden relative" style={{ zIndex: 45 }}>
          <div className="px-2 pt-2 pb-3 space-y-1 sm:px-3 bg-white border-b border-gray-100 shadow-lg">
            {navLinks.map((link) => (
              <a
                key={link.href}
                href={link.href}
                className="text-gray-600 hover:text-primary-dark block px-3 py-2 rounded-md text-base font-medium"
                onClick={() => setIsOpen(false)}
              >
                {link.name}
              </a>
            ))}
          </div>
        </div>
      )}
    </nav>
    </>
  );
};

export default Navbar;
