// stephen-taipei-react/src/components/Skills.jsx
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Code, Database, Server, Cpu } from 'lucide-react';
import { useLanguage } from '../i18n/LanguageContext';

const Skills = () => {
  const [activeTab, setActiveTab] = useState('Frontend');
  const { t, language } = useLanguage();
  const isChinese = language?.toLowerCase().startsWith('zh');

  const categories = [
    { id: 'Frontend', icon: Code, label: t.skills.frontend },
    { id: 'Backend', icon: Server, label: t.skills.backend },
    { id: 'DevOps', icon: Database, label: t.skills.devops },
    { id: 'AI', icon: Cpu, label: t.skills.ai },
  ];

  // Skills data based on resume - NO React/Vite
  const skillsData = {
    Frontend: [
      { name: 'Angular 19 (Signal / Computed / Effect)', level: 95 },
      { name: 'Nx Monorepo', level: 90 },
      { name: 'Vue.js', level: 80 },
      { name: 'jQuery', level: 85 },
      { name: 'PWA', level: 90 },
    ],
    Backend: [
      { name: 'Laravel Octane + Swoole', level: 95 },
      { name: 'WebSocket Server', level: 90 },
      { name: isChinese ? 'MySQL (讀寫分離)' : 'MySQL (Read/Write Separation)', level: 90 },
      { name: isChinese ? 'Redis (快取策略)' : 'Redis (Caching Strategy)', level: 90 },
      { name: 'PHP (Smarty)', level: 85 },
    ],
    DevOps: [
      { name: 'Ubuntu + Nginx', level: 90 },
      { name: 'Apache', level: 85 },
      { name: 'Docker', level: 80 },
      { name: 'GCP / Vultr', level: 85 },
      { name: 'Github CI/CD', level: 85 },
      { name: 'GitLab CI/CD', level: 85 },
    ],
    AI: [
      { name: 'OpenAI API', level: 95 },
      { name: 'Cursor + Claude + Codex + Gemini', level: 95 },
      { name: isChinese ? 'AI 繪圖應用' : 'AI Image Generation', level: 85 },
      { name: 'LINE / WeChat API', level: 85 },
      { name: isChinese ? '支付寶 / Google 串接' : 'Alipay / Google Integration', level: 85 },
    ]
  };

  return (
    <section id="skills" className="py-20 bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold text-gray-900">{t.skills.title}</h2>
          <p className="mt-4 text-gray-600">{t.skills.subtitle}</p>
        </div>

        <div className="flex flex-wrap justify-center gap-4 mb-12">
          {categories.map((cat) => (
            <button
              key={cat.id}
              onClick={() => setActiveTab(cat.id)}
              className={`flex items-center gap-2 px-6 py-3 rounded-full text-sm font-medium transition-all duration-300 ${
                activeTab === cat.id
                  ? 'bg-primary text-white shadow-lg shadow-primary/30'
                  : 'bg-white text-gray-600 hover:bg-gray-100'
              }`}
            >
              <cat.icon className="w-4 h-4" />
              {cat.label}
            </button>
          ))}
        </div>

        <div className="max-w-4xl mx-auto bg-white rounded-2xl p-8 shadow-sm border border-gray-100 min-h-[400px]">
          <motion.div
            key={activeTab}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
            className="grid grid-cols-1 md:grid-cols-2 gap-8"
          >
            {skillsData[activeTab].map((skill, index) => (
              <div key={index} className="space-y-2">
                <div className="flex justify-between items-end">
                  <span className="font-semibold text-gray-800">{skill.name}</span>
                  <span className="text-sm text-primary font-medium">{skill.level}%</span>
                </div>
                <div className="h-2 w-full bg-gray-100 rounded-full overflow-hidden">
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{ width: `${skill.level}%` }}
                    transition={{ duration: 0.8, delay: index * 0.1 }}
                    className="h-full bg-gradient-to-r from-primary to-secondary rounded-full"
                  />
                </div>
              </div>
            ))}
          </motion.div>
        </div>
      </div>
    </section>
  );
};

export default Skills;

// src/app/components/skills/skills.component.ts
import { Component, ElementRef, AfterViewInit, ViewChild, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

gsap.registerPlugin(ScrollTrigger);

interface Skill {
  name: string;
  level: number;
  color: 'cyan' | 'pink' | 'purple';
}

interface SkillCategory {
  id: string;
  title: string;
  icon: string;
  skills: Skill[];
}

@Component({
  selector: 'app-skills',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './skills.component.html',
  styleUrl: './skills.component.scss'
})
export class SkillsComponent implements AfterViewInit {
  @ViewChild('skillsSection') skillsSection!: ElementRef;

  activeCategory = signal('frontend');

  categories: SkillCategory[] = [
    {
      id: 'frontend',
      title: '前端開發',
      icon: 'M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4',
      skills: [
        { name: 'Angular', level: 95, color: 'cyan' },
        { name: 'TypeScript', level: 90, color: 'cyan' },
        { name: 'RxJS', level: 85, color: 'pink' },
        { name: 'TailwindCSS', level: 90, color: 'cyan' },
        { name: 'Vue.js', level: 75, color: 'purple' },
        { name: 'SCSS/CSS', level: 90, color: 'pink' },
      ]
    },
    {
      id: 'backend',
      title: '後端開發',
      icon: 'M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01',
      skills: [
        { name: 'Laravel', level: 90, color: 'pink' },
        { name: 'PHP', level: 88, color: 'purple' },
        { name: 'MySQL', level: 85, color: 'cyan' },
        { name: 'Redis', level: 82, color: 'pink' },
        { name: 'WebSocket', level: 80, color: 'cyan' },
        { name: 'Swoole', level: 75, color: 'purple' },
      ]
    },
    {
      id: 'devops',
      title: 'DevOps',
      icon: 'M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z',
      skills: [
        { name: 'Docker', level: 85, color: 'cyan' },
        { name: 'GitLab CI/CD', level: 82, color: 'pink' },
        { name: 'GCP', level: 78, color: 'cyan' },
        { name: 'Nginx', level: 80, color: 'purple' },
        { name: 'Linux/Ubuntu', level: 82, color: 'pink' },
        { name: 'Git', level: 90, color: 'cyan' },
      ]
    },
    {
      id: 'ai',
      title: 'AI 工具',
      icon: 'M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z',
      skills: [
        { name: 'Claude AI', level: 88, color: 'pink' },
        { name: 'Cursor AI', level: 85, color: 'cyan' },
        { name: 'OpenAI API', level: 82, color: 'purple' },
        { name: 'Prompt Engineering', level: 85, color: 'pink' },
        { name: 'AI Integration', level: 80, color: 'cyan' },
      ]
    }
  ];

  get activeSkills(): Skill[] {
    return this.categories.find(c => c.id === this.activeCategory())?.skills || [];
  }

  ngAfterViewInit() {
    this.initAnimations();
  }

  setActiveCategory(id: string) {
    this.activeCategory.set(id);
  }

  getColorClass(color: string): string {
    const colorMap: Record<string, string> = {
      cyan: 'from-neon-cyan to-cyan-400',
      pink: 'from-neon-pink to-pink-400',
      purple: 'from-deep-purple to-purple-400'
    };
    return colorMap[color] || colorMap['cyan'];
  }

  private initAnimations() {
    const section = this.skillsSection.nativeElement;

    gsap.from(section.querySelectorAll('.animate-on-scroll'), {
      scrollTrigger: {
        trigger: section,
        start: 'top 80%',
        toggleActions: 'play none none none'
      },
      opacity: 0,
      y: 50,
      duration: 0.8,
      stagger: 0.2,
      ease: 'power3.out'
    });
  }
}

<section id="skills" #skillsSection class="py-24 md:py-32 relative">
  <div class="container mx-auto px-4">
    <!-- Section Header -->
    <div class="text-center mb-16">
      <h2 class="section-title animate-on-scroll">
        <span class="text-gradient">技能專長</span>
      </h2>
      <p class="section-subtitle animate-on-scroll">Skills & Expertise</p>
    </div>

    <!-- Category Tabs -->
    <div
      class="flex flex-wrap justify-center gap-3 md:gap-4 mb-8 md:mb-12 animate-on-scroll"
    >
      @for (category of categories; track category.id) {
      <button
        class="category-tab flex items-center gap-2 px-4 py-2 md:px-6 md:py-3 text-sm md:text-base rounded-lg transition-all duration-300"
        [class.active]="activeCategory() === category.id"
        [class.glass-card]="activeCategory() !== category.id"
        (click)="setActiveCategory(category.id)"
      >
        <svg
          class="w-4 h-4 md:w-5 md:h-5"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            [attr.d]="category.icon"
          />
        </svg>
        <span>{{ category.title }}</span>
      </button>
      }
    </div>

    <!-- Skills Grid -->
    <div class="max-w-4xl mx-auto">
      <div class="grid md:grid-cols-2 gap-6">
        @for (skill of activeSkills; track skill.name; let i = $index) {
        <div
          class="skill-item glass-card rounded-xl p-6 hover-glow"
          [style.animation-delay]="i * 0.1 + 's'"
        >
          <!-- Skill Header -->
          <div class="flex justify-between items-center mb-3">
            <h4 class="font-semibold text-white">{{ skill.name }}</h4>
            <span
              class="text-sm font-medium"
              [class.text-neon-cyan]="skill.color === 'cyan'"
              [class.text-neon-pink]="skill.color === 'pink'"
              [class.text-purple-400]="skill.color === 'purple'"
            >
              {{ skill.level }}%
            </span>
          </div>

          <!-- Progress Bar -->
          <div class="h-2 bg-dark-gray rounded-full overflow-hidden">
            <div
              class="skill-bar h-full rounded-full bg-gradient-to-r transition-all duration-1000 ease-out"
              [class]="getColorClass(skill.color)"
              [style.width.%]="skill.level"
            ></div>
          </div>
        </div>
        }
      </div>
    </div>

    <!-- Tech Stack Icons -->
    <div class="mt-16 animate-on-scroll">
      <p class="text-center text-gray-400 mb-8">常用技術棧</p>
      <div class="flex flex-wrap justify-center gap-8 opacity-60">
        <!-- Angular -->
        <div class="tech-icon group cursor-default">
          <div
            class="w-16 h-16 rounded-lg glass-card flex items-center justify-center group-hover:border-neon-cyan transition-colors"
          >
            <span class="text-2xl font-bold text-neon-pink">Ng</span>
          </div>
          <span class="block text-xs text-center mt-2 text-gray-400"
            >Angular</span
          >
        </div>
        <!-- Laravel -->
        <div class="tech-icon group cursor-default">
          <div
            class="w-16 h-16 rounded-lg glass-card flex items-center justify-center group-hover:border-neon-pink transition-colors"
          >
            <span class="text-2xl font-bold text-neon-pink">La</span>
          </div>
          <span class="block text-xs text-center mt-2 text-gray-400"
            >Laravel</span
          >
        </div>
        <!-- TypeScript -->
        <div class="tech-icon group cursor-default">
          <div
            class="w-16 h-16 rounded-lg glass-card flex items-center justify-center group-hover:border-neon-cyan transition-colors"
          >
            <span class="text-2xl font-bold text-neon-cyan">TS</span>
          </div>
          <span class="block text-xs text-center mt-2 text-gray-400"
            >TypeScript</span
          >
        </div>
        <!-- Docker -->
        <div class="tech-icon group cursor-default">
          <div
            class="w-16 h-16 rounded-lg glass-card flex items-center justify-center group-hover:border-neon-cyan transition-colors"
          >
            <span class="text-2xl font-bold text-neon-cyan">Dk</span>
          </div>
          <span class="block text-xs text-center mt-2 text-gray-400"
            >Docker</span
          >
        </div>
        <!-- MySQL -->
        <div class="tech-icon group cursor-default">
          <div
            class="w-16 h-16 rounded-lg glass-card flex items-center justify-center group-hover:border-neon-pink transition-colors"
          >
            <span class="text-2xl font-bold text-neon-pink">My</span>
          </div>
          <span class="block text-xs text-center mt-2 text-gray-400"
            >MySQL</span
          >
        </div>
        <!-- Redis -->
        <div class="tech-icon group cursor-default">
          <div
            class="w-16 h-16 rounded-lg glass-card flex items-center justify-center group-hover:border-neon-pink transition-colors"
          >
            <span class="text-2xl font-bold text-neon-pink">Rd</span>
          </div>
          <span class="block text-xs text-center mt-2 text-gray-400"
            >Redis</span
          >
        </div>
      </div>
    </div>
  </div>

  <!-- Background Decoration -->
  <div
    class="absolute top-1/4 right-0 w-80 h-80 bg-neon-pink/5 rounded-full blur-3xl"
  ></div>
  <div
    class="absolute bottom-1/4 left-0 w-64 h-64 bg-neon-cyan/5 rounded-full blur-3xl"
  ></div>
</section>
